project:
  type: website
  output-dir: docs

website:
  title: "Maddie's Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - photography.qmd
      - portfolio.qmd

format:
  html:
    theme:
      - mystyles.scss
    mainfont: Times
    toc: true



