---
title: "Maddie's Page"
---

Hello, there!

Thanks for coming across my page! My name is Maddie Manzagol, I'm glad you're here!

Here's a little bit about me...


Hey all! My name is Maddie Manzagol. In my area of study, I’ve really enjoyed learning about ecosystem health and sustainable management in terms of restoration and development. I’m becoming increasingly interested in the intersection between urban wildlife and human activity and what these interactions mean for urban planning. I would like to explore more about how communities can implement green infrastructure in a way that mitigates environmental burdens and enhances equity for both wildlife and all community demographics.  In my free time, I enjoy hiking, trying new restaurants (especially sushi places), practicing capoeira, and spending quality time with friends and family. 


Some of my educational background: 

Currently I am a college undergraduate at the University of California, Santa Barbara pursuing an Environmental Studies B.S. degree with a concentration in Ecology, Evolution, and Marine Biology. Prior to my undergrad, I attended Saratoga High School in the Bay Area where I received my diploma.

More of my content: 

GitHub: <https://github.com/maddie-manzagol>
Linkedin: <https://www.linkedin.com/in/madeline-manzagol/> 